spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world?useSSL=false
    username: root
    password: password@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework: INFO
    com.hm: DEBUG



server:
  port: 8090